name:                Sync-GitHub-Issues
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/spamviech/Sync-GitHub-Issues#readme
license:             MIT
author:              spamviech
maintainer:          spamviech@web.de
copyright:           2021 spamviech
category:            Web
extra-source-files:
- README.md

dependencies:
- base >= 4.11 && < 5
- bytestring >= 0.10.12.1 && < 0.12
- directory >= 1.3.6.1 && < 1.4
- git-config >= 0.1.2 && < 0.2
- github >= 0.26 && < 0.27
- megaparsec >= 8 && < 9
- optparse-applicative >= 0.16.1 && < 0.17
- template-haskell >= 2.16 && < 2.17
- text >= 1.2.4.1 && < 1.3
- th-lift-instances >= 0.1.18 && < 0.2
- unordered-containers >= 0.2.13 && < 0.3
- vector >= 0.12.2 && < 0.13

ghc-options:
- -Wall

executables:
    Sync-Github-Issues:
        source-dirs:      src
        main:             Main.hs
